export const Gents = {
    title: "Gents Fashion",
    image1 :"assets/Men/1.jpg",
    image2 :"assets/Men/2.jpg",
    image3 :"assets/Men/3.jpg",
    image4 :"assets/Men/4.jpg",
    image5 :"assets/Men/5.jpg",
    image6 :"assets/Men/6.jpg",
    price1: "456 INR",
    price2: "356 INR",
    price3: "456 INR",
    price4: "457 INR",
    price5: "447 INR",
    price6: "256 INR",
}
export const Ladies = {
    title: "Ladies Fashion",
    image1 :"assets/Women/1.jpg",
    image2 :"assets/Women/2.jpg",
    image3 :"assets/Women/3.jpg",
    image4 :"assets/Women/4.jpg",
    image5 :"assets/Women/5.jpg",
    image6 :"assets/Women/6.jpg",
    price1: "456 INR",
    price2: "445 INR",
    price3: "435 INR",
    price4: "234 INR",
    price5: "345 INR",
    price6: "427 INR",
}